### ISSUE TITLE
Upgrade to SendGrid v3 Web API

### ISSUE THREAD

**Issue by thinkingserious** [krenfro/sendgrid-asm-java#6]
https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Thanks!

**Comment by krenfro** [comment]
It looks like the new v3 Java client from SendGrid supports ASM now.  If so, this project would no longer be needed.  Do you concur?

https://github.com/sendgrid/sendgrid-java/blob/master/USAGE.md#asm

**Comment by thinkingserious** [comment]
Agreed. Thanks!
